# Site
name: "B Réviews"
description: "Stories, News, Pictures and Videos"
meta_description: "Réviews | Beyoncé Knowles"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-121997922-1'
disqus: 'beyoncereviews'
mailchimp-list: 'https://eepurl.com/dAq9db'

# Authors
authors:

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge

permalink: /:year/:month/:day/:title:output_ext
